config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'blogs#index'
  get 'expenses_by_month', to: 'blogs#expenses_by_month', as: 'expenses_by_month'
  resources :blogs, params: :date, only: [:show]
  resources :incomes
  resources :expenses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :incomes
  has_many :expenses
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  
  def index
    @blogs = Blog.all
    @blog = Blog.new
    @expenses_by_date = Expense.group("DATE(date)").sum(:price)
  end

  def show
    date_string = params[:date]
    date_parts = date_string.split('-').map(&:to_i)
    formatted_date = "#{date_parts[0]}-#{date_parts[1].to_s.rjust(2, '0')}-#{date_parts[2].to_s.rjust(2, '0')}"
    @date = Date.parse(formatted_date)
    @incomes = Income.where("EXTRACT(YEAR FROM DATE(date)) = ? AND EXTRACT(MONTH FROM DATE(date)) = ? AND EXTRACT(DAY FROM DATE(date)) = ?", @date.year, @date.month, @date.day)
    @expenses = Expense.where("EXTRACT(YEAR FROM DATE(date)) = ? AND EXTRACT(MONTH FROM DATE(date)) = ? AND EXTRACT(DAY FROM DATE(date)) = ?", @date.year, @date.month, @date.day)
  end

  def expenses_by_month
    @year = params[:year].to_i
    @month = params[:month].to_i
    @expenses = Expense.where("YEAR(date) = ? AND MONTH(date) = ?", @year, @month)
    @total_expense = @expenses.sum(:price)
    @incomes = Income.where("YEAR(date) = ? AND MONTH(date) = ?", @year, @month)
    @total_income = @incomes.sum(:price)
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/expenses_by_month.html.erb
<h1><%= "#{@year}年#{@month}月" %></h1>

<div class= "income_expense_manthly_total">
  <p>収入合計: <%= @total_income %> 円</p>
  <p>支出合計: <%= @total_expense %> 円</p>
</div>


<div class="month_list">
  <table width="1500" border="1" align="center">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <!-- 変動費のカテゴリーを表示 -->
        <% ExpenseCategory.where(id: 2..9).each do |category| %>
          <th class="variable_expense"><%= category.name %></th>
        <% end %>
        <!-- 固定費のカテゴリーを表示 -->
        <% ExpenseCategory.where(id: 10..16).each do |category| %>
          <th class="fixed_expense"><%= category.name %></th>
        <% end %>
        <th>金額</th>
        <th>残額</th>
        <!-- 他に必要な列があれば追加してください -->
      </tr>
    </thead>
    <tbody>
      <% previous_day_balance = @total_income %>
      <% (1..31).each do |day| %>
        <% if Date.valid_date?(@year, @month, day) %>
          <tr>
            <td align="center"><%= "#{day}" %>日</td>
            <td align="center">
              <% japanese_days = ["日", "月", "火", "水", "木", "金", "土"] %>
              <%= japanese_days[Date.new(@year, @month, day).wday]%>
              <!-- 日付に対応する曜日を表示 -->
            </td>
            <% ExpenseCategory.where.not(id: 1).each do |category| %>
              <td align="center">
                <% expenses = @expenses.where(date: "#{@year}-#{@month}-#{day}", expense_category_id: category.id) %>
                <% total_price = expenses.sum(:price) %>
                <% if total_price > 0 %>
                  <%= total_price %>円
                <% end %>
              </td>
            <% end %>
            <% total_price = @expenses.where(date: "#{@year}-#{@month}-#{day}").sum(:price) %>
            <td align="right"><%= total_price %>円</td>
            <% total_expense = @expenses.where(date: "#{@year}-#{@month}-#{day}").sum(:price) %>
            <% daily_balance = previous_day_balance - total_expense %>
            <% previous_day_balance = daily_balance %>
            <td align="right">
              <%= daily_balance %>円
            </td>
            <% previous_day_balance = daily_balance %>

          </tr>
        <% end %>
      <% end %>
      <td align="center">合計</td>
      <td></td>
      <% ExpenseCategory.where.not(id: 1).each do |category| %>
        <td align="center">
          <% total_price = @expenses.where(expense_category_id: category.id).sum(:price) %>
          <%= total_price %>円
        </td>
      <% end %>
      <td align="right">
        <%= @expenses.sum(:price) %>円
      </td>
    </tbody>
  </table>
</div>

<%= pie_chart [["固定費", 300], ["変動費", 100], ["貯金", 80]] %>

app/views/blogs/index.html.erb
<div id="loading">
    <img class="spinner" src="images/loading.png" alt="" />
</div>

<div class="toppage">
  <h1 class="top">カレンダー</h1>
  <br>

  <br>
  <div class="col-md-8">
    <%= month_calendar events: @blogs do |date, blogs| %>
      <%= link_to blog_path(date, params: { date: "#{date.year}-#{date.month}-#{date.day}" }) do %>
        <%= date.day %>
      <% end %>
      <br>
      <br>

      <% total_expense = @expenses_by_date[date]  %>
      <% if total_expense.present? %>  
        <div class="total_price">
          <%= total_expense %> 円
        </div>
      <% end %>

      <% blogs.each do |blog| %>
          <%= link_to blog.title, blog %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="date">
  <%= @date %>
</div>

<div class="income-table">
  <div class="income-header">収入</div>
  <div class="list">
    <table width="800" border="1" align="center">
      <thead>
        <tr>
          <th>ユーザー</th>
          <th>種類</th>
          <th>金額</th>
        </tr>
      </thead>
      <tbody>
        <% @incomes.each do |income| %>
          <tr>
            <td align="center"><%= income.user.nickname %></td>
            <td align="center"><%= IncomeCategory.find(income.income_category_id).name %></td>
            <td align="center"><%= income.price %> 円</td>
            <td align="center">
              <%= link_to '編集', edit_income_path(income)  %>
              <%= link_to '削除', income_path(income), data: { turbo_method: :delete }  %>
              
            </td>            
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="expense-table">
  <h2 class="expense-header">支出</h2>
  <table width="800" border="1" align="center">
    <thead>
      <tr>
        <th>ユーザー</th>
        <th>種類</th>
        <th>支払方法</th>
        <th>金額</th>
      </tr>
    </thead>
    <tbody>
      <% @expenses.each do |expense| %>
        <tr>
          <td align="center"><%= expense.user.nickname %></td>
          <td align="center"><%= ExpenseCategory.find(expense.expense_category_id).name %></td>
          <td align="center"><%= PaymentMethod.find(expense.payment_method_id).name %></td>
          <td align="center"><%= expense.price %> 円</td>
          <td align="center">
            <%= link_to '編集', edit_expense_path(expense)  %>
            <%= link_to '削除', expense_path(expense), data: { turbo_method: :delete }  %>
          </td>          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>