config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'blogs#index'
  get 'expenses_by_month', to: 'blogs#expenses_by_month', as: 'expenses_by_month'
  resources :blogs, params: :date, only: [:show]
  resources :incomes
  resources :expenses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :incomes
  has_many :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user

  with_options presence: true do
    validates :date, :price, :user_id
    validates :expense_category_id, :payment_method_id, numericality: { other_than: 1, message: "can't be blank" } 
  end
end

app/models/expense_category.rb
class ExpenseCategory < ActiveHash::Base

  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '食費'},
    { id: 3, name: '外食'},
    { id: 4, name: 'コンビニ'},
    { id: 5, name: '日用品費'},
    { id: 6, name: '交際費'},
    { id: 7, name: '衣服費'},
    { id: 8, name: '医療費'},
    { id: 9, name: 'その他'},
    { id: 10, name: '家賃'},
    { id: 11, name: '電気代'},
    { id: 12, name: 'ガス代'},
    { id: 13, name: '水道代'},
    { id: 14, name: '電気代'},
    { id: 15, name: '保険'},
    { id: 16, name: '携帯代'},
    
  ]

  include ActiveHash::Associations
  has_many :expenses

  end

app/models/family.rb
class Family < ApplicationRecord
  has_many :users
  has_many :expenses, through: :users
  validates :name, presence: true

end

app/models/income.rb
class Income < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user

  with_options presence: true do
    validates :date, :price, :user_id
    validates :income_category_id, numericality: { other_than: 1, message: "can't be blank" } 
  end

end

app/models/income_category.rb
class IncomeCategory < ActiveHash::Base

  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '給与'},
    { id: 3, name: '賞与'},
    { id: 4, name: 'その他'},
  ]

  include ActiveHash::Associations
  has_many :incomes

  end

app/models/payment_method.rb
class PaymentMethod < ActiveHash::Base

  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: '現金'},
    { id: 3, name: 'カード'},
    { id: 4, name: 'QR決済'},
    { id: 5, name: '引き落とし'},
    { id: 6, name: 'その他'},
  ]

  include ActiveHash::Associations
  has_many :expenses

  end

  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :incomes
  has_many :expenses
  belongs_to :family, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password_confirmation])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  
  def index
    @blogs = Blog.all
    @blog = Blog.new
    @expenses_by_date = Expense.group("DATE(date)").sum(:price)
  end

  def show
    date_string = params[:date]
    date_parts = date_string.split('-').map(&:to_i)
    formatted_date = "#{date_parts[0]}-#{date_parts[1].to_s.rjust(2, '0')}-#{date_parts[2].to_s.rjust(2, '0')}"
    @date = Date.parse(formatted_date)
    @incomes = Income.where("EXTRACT(YEAR FROM DATE(date)) = ? AND EXTRACT(MONTH FROM DATE(date)) = ? AND EXTRACT(DAY FROM DATE(date)) = ?", @date.year, @date.month, @date.day)
    @expenses = Expense.where("EXTRACT(YEAR FROM DATE(date)) = ? AND EXTRACT(MONTH FROM DATE(date)) = ? AND EXTRACT(DAY FROM DATE(date)) = ?", @date.year, @date.month, @date.day)
  end

  def expenses_by_month
    @year = params[:year].to_i
    @month = params[:month].to_i
    @expenses = Expense.where("YEAR(date) = ? AND MONTH(date) = ?", @year, @month)
    @total_expense = @expenses.sum(:price)
    @incomes = Income.where("YEAR(date) = ? AND MONTH(date) = ?", @year, @month)
    @total_income = @incomes.sum(:price)
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)  
    if @expense.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    @expense.update(expense_params)
    redirect_to root_path
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    redirect_to root_path
  end

  private

  def expense_params
    params.require(:expense).permit(:date, :expense_category_id, :payment_method_id, :price).merge(user_id: current_user.id)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
  end

  def new
    @income = Income.new
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @income = Income.find(params[:id])
  end

  def update
    @income = Income.find(params[:id])
    @income.update(income_params)
    redirect_to root_path
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    redirect_to root_path
  end

  private

  def income_params
    params.require(:income).permit(:date, :income_category_id, :price).merge(user_id: current_user.id)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calender</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Allura&family=Lobster&family=Parisienne&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'header_styles' %>
    <%= javascript_importmap_tags %>
    <script src="js/menu.js" defer></script>
  </head>

  <body>
     <header class="header">
      <div class="heading">
        <h1 class="logo"><a href="/">Share money</a></h1>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
          
  
          <nav>
            <button id="menu-open" class="btn-menu">
              <svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                <title>メニューを開く</title>
                <path clip-rule="evenodd" d="m4.25 8c0-.41421.33579-.75.75-.75h14c.4142 0 .75.33579.75.75s-.3358.75-.75.75h-14c-.41421 0-.75-.33579-.75-.75zm0 4c0-.4142.33579-.75.75-.75h14c.4142 0 .75.3358.75.75s-.3358.75-.75.75h-14c-.41421 0-.75-.3358-.75-.75zm.75 3.25c-.41421 0-.75.3358-.75.75s.33579.75.75.75h14c.4142 0 .75-.3358.75-.75s-.3358-.75-.75-.75z" fill-rule="evenodd"/>
              </svg>
            </button>
            <div id="menu-panel">
              <button id="menu-close" class="btn-menu">
                <svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                  <title>メニューを閉じる</title>
                  <path clip-rule="evenodd" d="m7.53033 6.46967c-.29289-.29289-.76777-.29289-1.06066 0s-.29289.76777 0 1.06066l4.46963 4.46967-4.46963 4.4697c-.29289.2929-.29289.7677 0 1.0606s.76777.2929 1.06066 0l4.46967-4.4696 4.4697 4.4696c.2929.2929.7677.2929 1.0606 0s.2929-.7677 0-1.0606l-4.4696-4.4697 4.4696-4.46967c.2929-.29289.2929-.76777 0-1.06066s-.7677-.29289-1.0606 0l-4.4697 4.46963z" fill-rule="evenodd"/>
                </svg>
              </button>
              <ul class="menu-list">
                <% if user_signed_in? %>
                  <li class="nav-lists__list"><%= link_to current_user.nickname, "#" %></li>
                  <li class="nav-lists__list"><%= link_to '収入', new_income_path %></li>
                  <li class="nav-lists__list"><%= link_to '支出', new_expense_path %></li>
                  <li class="nav-lists__list"><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
                <% else %>
                  <li class="nav-lists__list"><%= link_to 'ログイン', new_user_session_path %></li>
                  <li class="nav-lists__list"><%= link_to '新規登録', new_user_registration_path %></li>
                <% end %>
              </ul>
            </div>
          </nav>
        </ul>
      </div>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view %>
    <span class="calendar-title">
      <%= link_to "#{start_date.year}年#{start_date.month}月", expenses_by_month_path(year: start_date.year, month: start_date.month) %>
    </span>
    <%= link_to t('simple_calendar.next', default: '翌月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>